--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/arvid/wallpapers/cyberpunk.jpg"

-- Special
background="#0B0B14"
foreground="#9dc6e6"
cursor="#9dc6e6"

-- Colors
color0="#0B0B14"
color1="#2D4674"
color2="#54415C"
color3="#BC4A75"
color4="#2E5B97"
color5="#4D5E9D"
color6="#406BC5"
color7="#9dc6e6"
color8="#6d8aa1"
color9="#2D4674"
color10="#54415C"
color11="#BC4A75"
color12="#2E5B97"
color13="#4D5E9D"
color14="#406BC5"
color15="#9dc6e6"
