--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/arvid/arcanes-dotfiles/wallpapers/WP-girl-winter-maple.jpg"

-- Special
background="#0d0f12"
foreground="#eee3d0"
cursor="#eee3d0"

-- Colors
color0="#0d0f12"
color1="#425A92"
color2="#666D91"
color3="#99768D"
color4="#A28984"
color5="#A49AA2"
color6="#DBA7A1"
color7="#eee3d0"
color8="#a69e91"
color9="#425A92"
color10="#666D91"
color11="#99768D"
color12="#A28984"
color13="#A49AA2"
color14="#DBA7A1"
color15="#eee3d0"
