# Shell variables
# Generated by 'wal'
wallpaper='/home/arvid/wallpapers/cyberpunk.jpg'

# Special
background='#0B0B14'
foreground='#9dc6e6'
cursor='#9dc6e6'

# Colors
color0='#0B0B14'
color1='#2D4674'
color2='#54415C'
color3='#BC4A75'
color4='#2E5B97'
color5='#4D5E9D'
color6='#406BC5'
color7='#9dc6e6'
color8='#6d8aa1'
color9='#2D4674'
color10='#54415C'
color11='#BC4A75'
color12='#2E5B97'
color13='#4D5E9D'
color14='#406BC5'
color15='#9dc6e6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
